[phases.setup]
nixPkgs = ["nodejs_22", "fontconfig"]

[phases.build]
cmds = ["npm install", "cd client && npm install && npm run build", "mkdir -p /usr/share/fonts/custom && cp fonts/*.ttf /usr/share/fonts/custom/ && fc-cache -f"]

[start]
cmd = "node server.js"
